modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/elucent/SimplyTea/issues"
license="MIT"

[[mods]]
modId="simplytea"
version="${file.jarVersion}"
displayName="Simply Tea"
displayURL="https://minecraft.curseforge.com/projects/simply-tea"
logoFile="simplytea.png"
credits="Original mod made by Elucent, who also designed most of the textures"
authors="Elucent, KnightMiner"
description='''
A simple tea mod made for /u/Pickles256 on Reddit!

Contains:
* Tea trees that spawn in your world!
* Teapots that you can fill with water and boil!
* Five types of tea: green, black, chai, floral, and chorus; with different effects!
'''
[[dependencies.simplytea]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.0,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.simplytea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"